# -*- coding: utf-8 -*-
"""entrega3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEo6CFrMCcWL4J1TWCyyDlMfe5yDmN_f

###Equipe:

- 🔹 Jenifer Barreto

- 🔹 Eduarda Lopes

- 🔹 Maria Kassandra

- 🔹 Flávio Santos
"""

!pip install dash

!pip install -U kaleido

import pandas as pd
dados_df=pd.read_excel('correlacaoIPCA.xlsx')

from dash import dcc, html, Input, Output
import dash
import plotly.express as px
import pandas as pd

# Carrega os dados
dados_df = pd.read_excel("correlacaoIPCA.xlsx")
dados_df.columns = dados_df.columns.str.strip()  # remove espaços extras
dados_df['Date'] = pd.to_datetime(dados_df['Date'])  # garante que Date seja datetime

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Dropdown(
        id='variavel-dropdown',
        options=[
            {'label': 'IPCA', 'value': 'IPCA'},
            {'label': 'SELIC', 'value': 'SELIC'},
            {'label': 'Inadimplência', 'value': 'Inadimplencia'}
        ],
        value='IPCA'
    ),
    dcc.Graph(id='grafico-variavel')
])

@app.callback(
    Output('grafico-variavel', 'figure'),
    Input('variavel-dropdown', 'value')
)
def update_graph(variavel):

    grouped_data = dados_df.groupby("Date", as_index=False)[variavel].mean() # Agrupa por data e calcula a média da variável escolhida

    fig = px.bar(grouped_data, x='Date', y=variavel, title=f'Dados do {variavel}')

    return fig

if __name__ == '__main__':
    app.run(debug=True)

"""Comparação de gráficos"""

from dash import dcc, html, Input, Output
import dash
import plotly.express as px
import pandas as pd

# Carrega os dados
dados_df = pd.read_excel("correlacaoIPCA.xlsx")
dados_df.columns = dados_df.columns.str.strip()  # remove espaços extras nos nomes das colunas

app = dash.Dash(__name__)


app.layout = html.Div([   # Layout com apenas um dropdown e gráfico
    html.Div([
        dcc.Dropdown(
            id='variavel-economica-dropdown',
            options=[
                {'label': 'IPCA', 'value': 'IPCA'},
                {'label': 'SELIC', 'value': 'SELIC'},
                {'label': 'Inadimplencia', 'value': 'Inadimplencia'}
            ],
            value='IPCA',
            placeholder="Escolha um indicador econômico"
        )
    ], style={'width': '50%', 'padding': '20px'}),

    html.Div([
        dcc.Graph(id='grafico-indicador-economico')
    ], style={'width': '90%', 'padding': '20px'})
])

# Callback para o gráfico
@app.callback(
    Output('grafico-indicador-economico', 'figure'),
    Input('variavel-economica-dropdown', 'value')
)
def update_indicador_economico(variavel):
    grouped_data = dados_df.groupby('Date', as_index=False)[variavel].mean()
    fig = px.line(grouped_data, x='Date', y=variavel,
                  title=f'Evolução de {variavel} ao longo do tempo')
    return fig

if __name__ == '__main__':
    app.run(debug=True)

"""**Gráfico de linha com a variação ao longo do tempo**"""

from dash import dcc, html, Input, Output
import dash
import plotly.express as px
import pandas as pd

# Carregar e preparar os dados
df = pd.read_excel("correlacaoIPCA.xlsx")
df.columns = df.columns.str.strip()  # Remover espaços em branco dos nomes das colunas

app = dash.Dash(__name__)

# Layout com dois gráficos
app.layout = html.Div([
    html.H2("Indicadores Econômicos"),

    html.Div([
        dcc.Graph(id='grafico-media-indicadores'),
        dcc.Graph(id='grafico-linha-indicadores')
    ])
])

# Callback para atualizar os dois gráficos
@app.callback(
    Output('grafico-media-indicadores', 'figure'),
    Output('grafico-linha-indicadores', 'figure'),
    Input('grafico-media-indicadores', 'id')  # Trigger de carregamento
)
def atualizar_graficos(_):
    # Gráfico de médias
    medias = df[['SELIC', 'IPCA', 'Inadimplencia']].mean().reset_index()
    medias.columns = ['Indicador', 'Média']
    fig_media = px.bar(medias, x='Indicador',  y='Média', title='Média dos Indicadores Econômicos')


    # Gráfico de linha temporal
    df['Date'] = pd.to_datetime(df['Date'])
    df_longo = df.melt(id_vars='Date', value_vars=['SELIC', 'IPCA', 'Inadimplencia'],
                       var_name='Indicador', value_name='Valor')
    fig_linha = px.line(df_longo, x='Date', y='Valor', color='Indicador',
                        title='Evolução dos Indicadores Econômicos ao Longo do Tempo')

    return fig_media, fig_linha


if __name__ == '__main__':
    app.run(debug=True)