# -*- coding: utf-8 -*-
"""entrega1_PI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQ2cm-vLK1AnFnSU5pMwbl3LkjIVJz-1
"""

!pip install python-bcb

#Taxa de juros sobre empréstimos
#Coleta de dados
from bcb import sgs
jurosMei = sgs.get({'selic': 432, 'saldoCred': 14026, 'inadimplencia': 15885}, start = '1999-01-01')
jurosMei = jurosMei.dropna()
jurosMei = jurosMei.reset_index()
print(jurosMei)

conj_jurosMei = sgs.get({'selic': 432, 'saldoCred': 14026, 'inadimplencia': 15885}, start = '1999-01-01')
conj_jurosMei = conj_jurosMei.dropna()
conj_jurosMei = conj_jurosMei.reset_index()
print(conj_jurosMei)

plt.scatter(conj_jurosMei.saldoCred, conj_jurosMei.inadimplencia)
plt.ylabel('saldoCred')
plt.xlabel('idadimplencia')
plt.show()